apiVersion: v1
kind: Service
metadata:
name: {{ template "prometheus-postgresql-adapter.fullname" . }}
labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
type: {{ .Values.service.type }}
ports:
- port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
selector:
    app: {{ template "prometheus-postgresql-adapter.fullname" . }}
